CREATE TABLE events (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL COMMENT '演出名称',
  type ENUM('concert','theatre','exhibition','sports','music','kids','dance') NOT NULL COMMENT '演出类型',
  artist VARCHAR(100) COMMENT '艺人/主办方',
  city VARCHAR(50) NOT NULL COMMENT '城市',
  venue_id BIGINT COMMENT '默认场馆ID',
  event_start_date DATE COMMENT '演出开始日期',
  event_end_date DATE COMMENT '演出结束日期',
  description TEXT COMMENT '演出简介',
  cover_image VARCHAR(500) COMMENT '封面图片URL',
  images JSON COMMENT '图片数组',
  status ENUM('draft','on_sale','off_sale','sold_out') NOT NULL DEFAULT 'draft' COMMENT '状态',
  sale_start_time DATETIME COMMENT '开售时间',
  sale_end_time DATETIME COMMENT '停售时间',
  tags JSON COMMENT '标签数组',
  metadata JSON COMMENT '扩展字段: {duration, tips, refund_policy}',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT COMMENT '创建人ID',
  FOREIGN KEY (venue_id) REFERENCES venues(id),
  INDEX idx_type (type),
  INDEX idx_city (city),
  INDEX idx_status (status),
  INDEX idx_artist (artist)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='演出表';