CREATE TABLE venues (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL COMMENT '场馆名称',
  city VARCHAR(50) NOT NULL COMMENT '所在城市',
  district VARCHAR(50) COMMENT '所在区域',
  address VARCHAR(500) NOT NULL COMMENT '详细地址',
  latitude DECIMAL(10,6) COMMENT '纬度',
  longitude DECIMAL(10,6) COMMENT '经度',
  capacity INT COMMENT '容纳人数',
  facilities JSON COMMENT '设施数组',
  description TEXT COMMENT '场馆介绍',
  images JSON COMMENT '场馆图片',
  metadata JSON COMMENT '扩展字段',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_city (city)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='场馆表';