CREATE TABLE sessions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  event_id BIGINT NOT NULL COMMENT '所属演出ID',
  session_name VARCHAR(200) COMMENT '场次名称',
  start_time DATETIME NOT NULL COMMENT '场次开始时间',
  end_time DATETIME COMMENT '场次结束时间',
  venue_id BIGINT NOT NULL COMMENT '场馆ID',
  hall_name VARCHAR(100) COMMENT '馆厅名称',
  address VARCHAR(500) COMMENT '详细地址',
  total_seats INT NOT NULL COMMENT '总座位数',
  available_seats INT NOT NULL DEFAULT 0 COMMENT '可售座位数',
  sold_seats INT NOT NULL DEFAULT 0 COMMENT '已售座位数',
  locked_seats INT NOT NULL DEFAULT 0 COMMENT '锁定座位数',
  status ENUM('not_started','on_sale','sold_out','ended','off_sale') NOT NULL DEFAULT 'not_started' COMMENT '状态',
  seat_map_config JSON COMMENT '座位图配置',
  ticket_tier_config JSON COMMENT '票档配置',
  metadata JSON COMMENT '扩展字段',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
  FOREIGN KEY (venue_id) REFERENCES venues(id),
  INDEX idx_event_id (event_id),
  INDEX idx_start_time (start_time),
  INDEX idx_status (status),
  INDEX idx_venue_id (venue_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='场次表';